IgnorePath '*.bak'
IgnorePath '*.key'
IgnorePath '*.pacnew'
IgnorePath '*.pacsave'
IgnorePath '*.sbak'

IgnorePath '/boot/*'

IgnorePath '/efi/*'

IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/.updated'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/ca-certificates/*'
IgnorePath '/etc/credstore.encrypted'
IgnorePath '/etc/credstore'
IgnorePath '/etc/cups/*.O'
IgnorePath '/etc/cups/ppd/*.O'
IgnorePath '/etc/cups/ssl/*'
IgnorePath '/etc/cups/subscriptions*'
IgnorePath '/etc/docker/key.json'
IgnorePath '/etc/fonts/*'
IgnorePath '/etc/group-'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/lvm/cache/.cache'
IgnorePath '/etc/machine-id'
IgnorePath '/etc/mail/*'
IgnorePath '/etc/mkinitcpio.d/*'
IgnorePath '/etc/NetworkManager/system-connections/*'
IgnorePath '/etc/os-release'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/pacman.d/mirrorlist'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/pki/*'
IgnorePath '/etc/printcap'
IgnorePath '/etc/proxydriver.d/*'
IgnorePath '/etc/rslsync.conf'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/shells'
IgnorePath '/etc/ssh/ssh_host_*'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/subgid-'
IgnorePath '/etc/subuid-'
IgnorePath '/etc/texmf/*'
IgnorePath '/etc/xml'

IgnorePath '/logs/*'

IgnorePath '/lost+found'

IgnorePath '/opt/*'

IgnorePath '/srv/craftbukkit/*'

IgnorePath '/usr/*'

IgnorePath '/var/*'